version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=questionnaire
    volumes:
      - questionnaire_pg_data:/bitnami/postgres


  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'questionnaire_redis_data:/bitnami/redis/data'

volumes:
  questionnaire_pg_data:
  questionnaire_redis_data: